### ISSUE TITLE
Paper's PDF link

### ISSUE THREAD

**Issue by fawnliu** [google/referring-manipulation#1]
Dear author, can you release a pdf link or BibTeX of this paper?

**Comment by myungsub** [comment]
Hello @scarleatt , thanks for your interest in my work.

I've updated the link [[here](https://github.com/google/referring-manipulation/pull/2)]. For the quick link, you can check the paper PDF **[here](https://www.ecva.net/papers/eccv_2022/papers_ECCV/html/5859_ECCV_2022_paper.php)** and the corresponding bibtex as below:
```
@InProceedings{Choi_2022_ECCV,
  author = {Choi, Myungsub},
  title = {Referring Object Manipulation of Natural Images using Conditional Classifier-free Guidance},
  booktitle = {Proceedings of the European Conference on Computer Vision (ECCV)},
  month = {October},
  year = {2022}
}
```

**Comment by fawnliu** [comment]
Thanks for your prompt reply.
